MIPS: MSP71xx: Fix missing asm/setup.h include
Building msp71xx_defconfig currently fails due to a missing inclusion of
asm/setup.h leading to:

  arch/mips/pmcs-msp71xx/msp_smp.c: In function ‘msp_vsmp_int_init’:
  arch/mips/pmcs-msp71xx/msp_smp.c:72:2: error: implicit declaration of
  function ‘set_vi_handler’ [-Werror=implicit-function-declaration]
    set_vi_handler(MIPS_CPU_IPI_RESCHED_IRQ, ipi_resched_dispatch);
    ^
  cc1: all warnings being treated as errors

Fix this by including asm/setup.h to obtain the declaration of
set_vi_handler().

Signed-off-by: Paul Burton <paul.burton@imgtec.com>