fixup! MIPS: nanoMIPS uprobes support
This patch causes compilation errors for non-nanomips defconfigs:

arch/mips/kernel/uprobes.c: In function ‘arch_uprobe_copy_ixol’:
arch/mips/kernel/uprobes.c:269:45: error: request for member ‘h’ in
something not a structure or union
    for (j = 0; j < (nanomips_insn_len(ops[i].h[0]) / 2); j++)
                                             ^
arch/mips/kernel/uprobes.c:270:22: error: request for member ‘h’ in
something not a structure or union
     buf[d++] = ops[i].h[j];
                      ^
make[2]: *** [scripts/Makefile.build:316: arch/mips/kernel/uprobes.o]
Error 1
make[2]: *** Waiting for unfinished jobs....
  CC      mm/slab_common.o
make[1]: *** [scripts/Makefile.build:575: arch/mips/kernel] Error 2
make: *** [Makefile:1019: arch/mips] Error 2
make: *** Waiting for unfinished jobs....

Fix by wrapping in #ifdef __nanomips__, as used in the reset of the
file, rather than if (cpu_has_nanomips)