MIPS: Don't define CAC_BASE generically if platform did
When CONFIG_64BIT=y we already guard the generic definition of CAC_BASE
to allow for systems to override it. With CONFIG_32BIT=y we do not. This
may make sense given that on MIPS32 systems, ignoring EVA, you'd
essentially always want to use kseg0 whilst on MIPS64 systems you may
wish to specify a particular xkphys region corresponding to your desired
CCA.

In any case whether or not it makes sense for 32 bit platforms to
specify their own CAC_BASE, we can & do now build code for 64 bit
platforms with CONFIG_32BIT=y for the VDSO... Any system defining its
own CAC_BASE thus hits a build error during the compilation of 32 bit
VDSOs, for example:

  In file included from ../arch/mips/include/asm/mach-ip27/spaces.h:29:0,
                   from ../arch/mips/include/asm/page.h:12,
                   from ../arch/mips/vdso/vdso.h:26,
                   from ../arch/mips/vdso/gettimeofday.c:11:
  ../arch/mips/include/asm/mach-generic/spaces.h:28:0: error: "CAC_BASE"
  redefined [-Werror]
   #define CAC_BASE  _AC(0x80000000, UL)
   ^

A full build log from an affected ip27 configuration can be found at:

  https://storage.kernelci.org/net-next/v4.9-rc3-535-gd8e4aa070751/mips-ip27_defconfig/build.log

Fix the broken builds by avoiding the generic CONFIG_32BIT CAC_BASE
definition if the platform code already defined one. The ideal fix would
be for the VDSO to not do crazy things, but for now...

Signed-off-by: Paul Burton <paul.burton@imgtec.com>